{% set version = "1.25" %}

package:
  name: harp
  version: {{ version }}

source:
  url: https://github.com/stcorp/harp/releases/download/{{ version }}/harp-{{ version }}.tar.gz
  sha256: 91d65e0ee6cfc02dc9ae150e750b460eaf5c1fb6b457b6651681ceef19114975

build:
  number: 0
  script_env:
    - HARP_BUILD_R=True  # [not arm64]
    - HARP_BUILD_R=False  # [arm64]
  rpaths:
    - lib/R/lib
    - lib

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake

outputs:
  - name: harp
    script: install.sh  # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [not win]
        - bison  # [not win]
        - flex  # [not win]
        - m2-bison  # [win]
        - m2-flex  # [win]

      host:
        - coda
        - python
        - hdf4
        - hdf5
        - r-base  # [win]
        - r-base >=4.2  # [not win and not arm64]

      run:
        - python
        - cffi  # [python_impl != 'pypy']
        - coda
        - numpy

    test:
      commands:
        - test -f $PREFIX/lib/libharp$SHLIB_EXT  # [unix]
        - if not exist "%LIBRARY_PREFIX%/lib/libharp.lib" exit 1  # [win]
        - if not exist "%LIBRARY_PREFIX%/bin/harpdump.exe" exit 1  # [win]
      imports:
        - harp

  - name: r-harp
    script: install.sh  # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [not win]
        - bison  # [not win]
        - flex  # [not win]
        - m2-bison  # [win]
        - m2-flex  # [win]

      host:
        - coda
        - python
        - hdf4
        - hdf5
        - r-base  # [win]
        - r-base >=4.2  # [not win and not arm64]

      run:
        - harp
        - r-base  # [win]
        - r-base >=4.2  # [not win and not arm64]

    test:
      commands:
        - $R -e "library('harp')"  # [unix and not arm64]
        - "\"%R%\" -e \"library('harp')\""  # [win]

about:
  home: https://github.com/stcorp/harp
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: COPYING
  summary: HARP is a toolset for ingesting, processing and inter-comparing satellite or model data against correlative data. The toolset is composed of a set of command line tools, a C library of analysis functions, and import/export interfaces for Python, R, Matlab, and IDL.

extra:
  recipe-maintainers:
    - svniemeijer
