{% set version = "1.17" %}

package:
  name: harp
  version: {{ version }}

source:
  url: https://github.com/stcorp/harp/releases/download/{{ version }}/harp-{{ version }}.tar.gz
  sha256: a94fb1c1bb660cbb8735abe548e821b2b55c9429cb57537a7fd186fbb86ac5c4

build:
  number: 1
  script_env:
    - HARP_BUILD_R=True  # [not arm64]
    - HARP_BUILD_R=False  # [arm64]
  rpaths:
    - lib/R/lib
    - lib

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cross-r-base {{ r_base }}  # [build_platform != target_platform and not arm64]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

outputs:
  - name: harp
    script: install.sh  # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cross-r-base {{ r_base }}  # [build_platform != target_platform and not arm64]
        - gnuconfig  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [not win]
        - bison  # [not win]
        - flex  # [not win]
        - m2-bison  # [win]
        - m2-flex  # [win]

      host:
        - coda
        - python
        - zlib
        - hdf4
        - hdf5
        - jpeg
        - r-base  # [not arm64]

      run:
        - python
        - cffi  # [python_impl != 'pypy']
        - coda
        - numpy

    test:
      commands:
        - test -f $PREFIX/lib/libharp$SHLIB_EXT  # [unix]
        - if not exist "%LIBRARY_PREFIX%/lib/libharp.lib" exit 1  # [win]
        - if not exist "%LIBRARY_PREFIX%/bin/harpdump.exe" exit 1  # [win]
      imports:
        - harp

  - name: r-harp
    script: install.sh  # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cross-r-base {{ r_base }}  # [build_platform != target_platform and not arm64]
        - gnuconfig  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [not win]
        - bison  # [not win]
        - flex  # [not win]
        - m2-bison  # [win]
        - m2-flex  # [win]

      host:
        - coda
        - python
        - zlib
        - hdf4
        - hdf5
        - jpeg
        - r-base  # [not arm64]

      run:
        - harp
        - r-base  # [not arm64]

    test:
      commands:
        - $R -e "library('harp')"  # [unix]
        - "\"%R%\" -e \"library('harp')\""  # [win]

about:
  home: https://github.com/stcorp/harp
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: COPYING
  summary: HARP is a toolset for ingesting, processing and inter-comparing satellite or model data against correlative data. The toolset is composed of a set of command line tools, a C library of analysis functions, and import/export interfaces for Python, R, Matlab, and IDL.

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
